name: video_app
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  encrypt: ^5.0.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  image_picker: ^0.8.7+5
  injectable: ^2.1.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  path_provider: ^2.0.15
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.1.1
  video_player: ^2.6.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21   

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
 